package A03;
import java.util.*;


public class MyQuestion {
	public static void main(String[] args) {
		String ques[]= {"1.who is fathr of software Engineering?1) Margaret Hamiltona 2) Watts S. Humphrey 3) Alan Turing 4) Boris Beizer","2. ____________ is a software development activity that is not a part of software processes.1) Validation 2) Specification 3) Development 4)Dependence","3.What are the features of Software Code?1) Simplicity 2) Accessibility 3)Modularity 4)All of the above",
"4.Java Source Code is compiled into ______________. 1) .Obj 2) Source Code 3) Bytecode 4) .Exe","5.What is byte code in Java? 1)Code generated by a Java compiler 2)Code generated by a Java Virtual Machine 3)Name of Java source code file 4)Block of code written inside a"};
		int ans[] = {1,2,3,4,5};
		int m=0,r=0;
		Scanner sc = new Scanner(System.in);
		for(int i = 0;i < ques.length;i++) {
		System.out.println(ques[i]);
		System.out.println("ans correct from following");
		int ans1=sc.nextInt();
		if(ans[i]==ans1) {
			m++;
		}
		else {
			r++;
		}
		}
		System.out.println("Total Mark"+ (5-r));
		System.out.println("total marks "+ 5);
}
}
